### ISSUE TITLE
Consolidated table of all 600 articles that comprise LSD600

### ISSUE THREAD

**Issue by dhimmel** [EsmaeilNourani/lifestylefactors-entities-annotation-docs#2]
I'm reviewing the preprint [LSD600: the first corpus of biomedical abstracts annotated with lifestyle–disease relations](https://doi.org/10.1101/2024.08.30.24312862).

It would be helpful to have a single table of all 600 abstracts comprising the LSD600 corpus.

Columns that come to my mind are:

- pubmed id
- journal
- publication year
- title
- number of disease entities
- number of LSF entities
- number of relations
- dev/train/test category
- abstract text

And perhaps you can think of more.

The goal here is to have an accessible reference of all abstracts in the corpus and their metadata.

**Comment by EsmaeilNourani** [comment]
Thank you for your comment and for reviewing the preprint! We appreciate your suggestion, and we will provide this table as metadata about the LSD600 corpus soon.

**Comment by EsmaeilNourani** [comment]
I’m pleased to inform you that the metadata file you requested is now available. It includes a comprehensive table of all 600 abstracts in the LSD600 corpus with the following columns:

- **Publication ID**
- **Article Title**
- **Journal Name**
- **Publication Year**
- **Data Set (Dev/Train/Test Category)**
- **Lifestyle Factor Count**
- **Disease Count**
- **Relations Count**
- **Abstract Text**
- **Unique Lifestyle Factors**
- **Unique Diseases**

You can access the file on Zenodo, where the LSD600 corpus is located:

🔗 [LSD600 Metadata File](https://zenodo.org/records/13952449/files/LSD600_metadata.tsv)

Additionally, I’ve provided the code for generating this table as requested: 

🔗 [Generate Metadata](https://github.com/EsmaeilNourani/LSF_Disease_RE/blob/main/helpers/create_metadata.py)

We appreciate your suggestions @dhimmel  and hope these resources are helpful for your review!

**Comment by dhimmel** [comment]
Very helpful. I see the `LSD600_metadata.tsv` on the [Zenodo](https://doi.org/10.5281/zenodo.13952449) and the contents look good.

Closing this issue and the corresponding request in [my review](https://prereview.org/reviews/13869488) should be considered addressed!
