### ISSUE TITLE
Inconsistencies in relation labels and capitalization

### ISSUE THREAD

**Issue by dhimmel** [EsmaeilNourani/lifestylefactors-entities-annotation-docs#3]
From [Table S1](https://www.medrxiv.org/content/10.1101/2024.08.30.24312862v1.full-text), we see how the manusript refers to the relation types:

![image](https://github.com/user-attachments/assets/5c80da8d-a537-46c1-8681-f15d5d602cbc)

Now in the [code](https://github.com/EsmaeilNourani/LSF_Disease_RE/blob/9895a5e0ffc6d2eddc349204750fc702a95790da/UseRelationExtractionPipeline/LSF_DIS_rel_configs.json#L7-L56) and data, we see the following types:

```
Causes
Controls
Prevents
Treats
Statistically_associated
positive_statistical_association
negative_statistical_association
NO_statistical_association
```

A couple things jumped out at me:

1. `Statistically_associated` is morphologically different in terms of word forms than `positive_statistical_association`. If `Statistically_associated` were `statistical_association`, this difference would be resolved.
2. There is inconsistent casing.

This is pretty minor and might be laborious to fix across all the code and data. OTOH I believe this study is proposing this hierarchy of relations as original content with the intent that future projects can reuse it, so it would be unfortunate to start it with these imperfections that will only be harder to fix down the road.

**Comment by EsmaeilNourani** [comment]
Thank you for your feedback! We have updated the entire codebase on [GitHub](https://github.com/EsmaeilNourani/LSF_Disease_RE/tree/main) and the LSD600 corpus on [Zenodo](https://zenodo.org/records/13952449) to ensure consistency in the relation type names. The corrected relation types are as follows:

- `causes`
- `controls`
- `prevents`
- `treats`
- `statistical_association`
- `positive_statistical_association`
- `negative_statistical_association`
- `no_statistical_association`

Additionally, the entity names have been changed to:

- `lifestyle_factor`
- `disease`

These updates have been applied across all code, the corpus, BRAT annotation configurations, and the trained model.

We appreciate your observations regarding the naming conventions.

**Comment by dhimmel** [comment]
Nicely done!
